"""Generate recognition_events seed data from the *actual trained model's*
predictions on its held-out test set -- not fabricated numbers.

Confidence scores are real (same model, same test split train.py
evaluated on). Camera assignment and timestamps are synthesized, since
LFW has no such metadata -- including one deliberate cluster of
impostor (is_genuine_attempt=False) events at one camera within a
5-minute window, so the anomaly-detection queries have something real
to catch.

Run from db-analytics/: python generate_events.py > seed_data.sql
"""
import datetime
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ml-service", "src"))

from data import load_binary_face_dataset, split_dataset
from inference import load_artifact

RANDOM_STATE = 42
CAMERAS = [
    ("Main Entrance", "Lobby"),
    ("Server Room", "Restricted"),
    ("Parking Garage", "Perimeter"),
    ("Executive Floor", "Restricted"),
]
CAMERA_WEIGHTS = [0.55, 0.15, 0.20, 0.10]  # main entrance sees the most traffic
PERSON_NAME = "Arnold Schwarzenegger"
DAYS_OF_HISTORY = 30
BURST_SIZE = 5  # number of impostor attempts in the injected anomaly


def sql_literal(value):
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return str(value)


def main():
    rng = random.Random(RANDOM_STATE)
    model, image_shape, threshold = load_artifact()

    X, y, _ = load_binary_face_dataset()
    _, X_test, _, y_test = split_dataset(X, y)
    confidences = model.predict_proba(X_test)[:, 1]

    now = datetime.datetime(2026, 7, 15, 12, 0, 0)  # fixed for reproducibility

    events = []
    for confidence, is_genuine in zip(confidences, y_test):
        camera_idx = rng.choices(range(len(CAMERAS)), weights=CAMERA_WEIGHTS)[0]
        days_ago = rng.randint(0, DAYS_OF_HISTORY - 1)
        hour = rng.uniform(7, 21) if rng.random() < 0.85 else rng.uniform(0, 24)
        base_date = (now - datetime.timedelta(days=days_ago)).date()
        ts = datetime.datetime.combine(base_date, datetime.time()) + datetime.timedelta(hours=hour)
        events.append(
            {
                "camera_idx": camera_idx,
                "confidence": float(confidence),
                "is_genuine": bool(is_genuine),
                "timestamp": ts,
            }
        )

    # Inject one deliberate anomaly: pick BURST_SIZE impostor (non-genuine)
    # events and cluster them at one camera within a 5-minute window, as if
    # someone made repeated spoofing attempts.
    impostor_indices = [i for i, e in enumerate(events) if not e["is_genuine"]]
    burst_indices = rng.sample(impostor_indices, BURST_SIZE)
    burst_camera_idx = 1  # "Server Room" -- a restricted zone, worth flagging
    burst_start = now - datetime.timedelta(days=3, hours=2)  # 3 days ago, 2am
    for i, idx in enumerate(burst_indices):
        events[idx]["camera_idx"] = burst_camera_idx
        events[idx]["timestamp"] = burst_start + datetime.timedelta(minutes=i * 0.8)

    events.sort(key=lambda e: e["timestamp"])

    print("-- Generated by db-analytics/generate_events.py -- do not edit by hand.")
    print(f"-- {len(events)} events; confidence scores are real model output, ")
    print(f"-- camera/timestamp metadata is synthesized (including a deliberate")
    print(f"-- {BURST_SIZE}-event impostor burst at Server Room for the anomaly queries).")
    print()
    print(f"INSERT INTO persons (name) VALUES ({sql_literal(PERSON_NAME)});")
    print()
    print("INSERT INTO cameras (location, zone) VALUES")
    print(",\n".join(f"    ({sql_literal(loc)}, {sql_literal(zone)})" for loc, zone in CAMERAS) + ";")
    print()

    print("INSERT INTO recognition_events")
    print("    (camera_id, claimed_person_id, confidence_score, threshold_used, is_match, is_genuine_attempt, event_timestamp)")
    print("VALUES")
    rows = []
    for e in events:
        camera_id = e["camera_idx"] + 1  # SERIAL ids start at 1, inserted in CAMERAS order
        is_match = e["confidence"] >= threshold
        rows.append(
            "    ({camera_id}, 1, {conf:.4f}, {thr:.4f}, {match}, {genuine}, {ts})".format(
                camera_id=camera_id,
                conf=e["confidence"],
                thr=threshold,
                match=sql_literal(is_match),
                genuine=sql_literal(e["is_genuine"]),
                ts=sql_literal(e["timestamp"].strftime("%Y-%m-%d %H:%M:%S")),
            )
        )
    print(",\n".join(rows) + ";")


if __name__ == "__main__":
    main()
